### ISSUE TITLE
Response value ranges in emotion GET /media/

### ISSUE THREAD

**Issue by petarsubotic** [kairosinc/api-examples#1]
Where could one find out more details about response ranges in GET /media/{id}.

We are attempting to combine the individual charts for smile, surprise, negative and attention into one and are running into issues (have lack of confidence in accurate representation) with translating our min-max values.

Are the response values standardized, is there any documentation available around this?

**Comment by coleca** [comment]
Yes, the response values are all between 0 and 100 (floating point values) for each element.
