### ISSUE TITLE
I'm getting 502 Bad Gateway

### ISSUE THREAD

**Issue by rubemfsv** [kairosinc/api-examples#10]
I'm following the tutorial perfectly, but, when I'm going to access the page, I'm getting 502 Bad Gateway.

How can I fix it up?

**Comment by josue** [comment]
I was able to build and run the api example, but i'm not getting an HTTP 502 response when i curl the website. Could you explain where exactly you're seeing the 502 error.

_container build and curl preview:_
[![asciicast](https://asciinema.org/a/00nwc5xhdripf62kdfhs8xr90.png)](https://asciinema.org/a/00nwc5xhdripf62kdfhs8xr90)

**Comment by rubemfsv** [comment]
I did the same thing as you do, and I got bad gateway. 

Rubem$ curl http://localhost:8080
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.1</center>
</body>
</html>

**Comment by coleca** [comment]
Can you post the output of `docker-compose logs` ?

**Comment by rubemfsv** [comment]
Rubem$ docker-compose logs -f
Attaching to demo_demo_1
demo_1  | fetch http://nl.alpinelinux.org/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
demo_1  | fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
demo_1  | fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
demo_1  | (1/1) Installing php5-xdebug (2.5.0-r1)
demo_1  | OK: 176 MiB in 82 packages
demo_1  | 2017-05-18 16:41:25,360 CRIT Set uid to user 0
demo_1  | 2017-05-18 16:41:25,372 INFO RPC interface 'supervisor' initialized
demo_1  | 2017-05-18 16:41:25,372 CRIT Server 'unix_http_server' running without any HTTP authentication checking
demo_1  | 2017-05-18 16:41:25,372 INFO supervisord started with pid 39
demo_1  | 2017-05-18 16:41:26,376 INFO spawned: 'php-fpm' with pid 42
demo_1  | 2017-05-18 16:41:26,388 INFO spawned: 'nginx' with pid 43
demo_1  | [18-May-2017 16:41:26] WARNING: Nothing matches the include pattern '/etc/php5/fpm.d/*.conf' from /etc/php5/php-fpm.conf at line 15.
demo_1  | [18-May-2017 16:41:26] ERROR: [/etc/php5/php-fpm.conf:544] empty value
demo_1  | [18-May-2017 16:41:26] ERROR: failed to load configuration file '/etc/php5/php-fpm.conf'
demo_1  | [18-May-2017 16:41:26] ERROR: FPM initialization failed
demo_1  | 2017-05-18 16:41:26,426 INFO exited: php-fpm (exit status 78; not expected)
demo_1  | 2017-05-18 16:41:27,431 INFO spawned: 'php-fpm' with pid 46
demo_1  | 2017-05-18 16:41:27,432 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
demo_1  | [18-May-2017 16:41:27] WARNING: Nothing matches the include pattern '/etc/php5/fpm.d/*.conf' from /etc/php5/php-fpm.conf at line 15.
demo_1  | [18-May-2017 16:41:27] ERROR: [/etc/php5/php-fpm.conf:544] empty value
demo_1  | [18-May-2017 16:41:27] ERROR: failed to load configuration file '/etc/php5/php-fpm.conf'
demo_1  | [18-May-2017 16:41:27] ERROR: FPM initialization failed
demo_1  | 2017-05-18 16:41:27,466 INFO exited: php-fpm (exit status 78; not expected)
demo_1  | 2017-05-18 16:41:29,476 INFO spawned: 'php-fpm' with pid 47
demo_1  | [18-May-2017 16:41:29] WARNING: Nothing matches the include pattern '/etc/php5/fpm.d/*.conf' from /etc/php5/php-fpm.conf at line 15.
demo_1  | [18-May-2017 16:41:29] ERROR: [/etc/php5/php-fpm.conf:544] empty value
demo_1  | [18-May-2017 16:41:29] ERROR: failed to load configuration file '/etc/php5/php-fpm.conf'
demo_1  | [18-May-2017 16:41:29] ERROR: FPM initialization failed
demo_1  | 2017-05-18 16:41:29,514 INFO exited: php-fpm (exit status 78; not expected)
demo_1  | 2017-05-18 16:41:32,527 INFO spawned: 'php-fpm' with pid 48
demo_1  | [18-May-2017 16:41:32] WARNING: Nothing matches the include pattern '/etc/php5/fpm.d/*.conf' from /etc/php5/php-fpm.conf at line 15.
demo_1  | [18-May-2017 16:41:32] ERROR: [/etc/php5/php-fpm.conf:544] empty value
demo_1  | [18-May-2017 16:41:32] ERROR: failed to load configuration file '/etc/php5/php-fpm.conf'
demo_1  | [18-May-2017 16:41:32] ERROR: FPM initialization failed
demo_1  | 2017-05-18 16:41:32,570 INFO exited: php-fpm (exit status 78; not expected)
demo_1  | 2017-05-18 16:41:33,574 INFO gave up: php-fpm entered FATAL state, too many start retries too quickly
demo_1  | 172.19.0.1 - - [18/May/2017:16:42:39 +0000] "GET / HTTP/1.1" 502 173 "-" "curl/7.51.0"
demo_1  | 2017/05/18 16:42:39 [crit] 45#0: *1 connect() to unix:/var/run/php-fpm.sock failed (13: Permission denied) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost:8080"
demo_1  | 2017/05/18 16:42:55 [crit] 45#0: *3 connect() to unix:/var/run/php-fpm.sock failed (13: Permission denied) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost:8080"
demo_1  | 172.19.0.1 - - [18/May/2017:16:42:55 +0000] "GET / HTTP/1.1" 502 173 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30"
demo_1  | 2017/05/18 16:45:05 [crit] 45#0: *5 connect() to unix:/var/run/php-fpm.sock failed (13: Permission denied) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost:8080"
demo_1  | 172.19.0.1 - - [18/May/2017:16:45:05 +0000] "GET / HTTP/1.1" 502 173 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30"
demo_1  | 172.19.0.1 - - [18/May/2017:16:57:55 +0000] "GET / HTTP/1.1" 502 173 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30"
demo_1  | 2017/05/18 16:57:55 [crit] 45#0: *7 connect() to unix:/var/run/php-fpm.sock failed (13: Permission denied) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost:8080"

**Comment by coleca** [comment]
Are you sure you have the latest code pulled down?  We fixed this issue last week.

**Comment by rubemfsv** [comment]
Yes. I'm sure. By the way, I deleted and cloned, and did everything again, but the error stays. 

Follow the logs:

Rubem$ docker-compose logs -f
Attaching to demo_demo_1
demo_1  | fetch http://nl.alpinelinux.org/alpine/latest-stable/community/x86_64/APKINDEX.tar.gz
demo_1  | fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
demo_1  | fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
demo_1  | (1/1) Installing php5-xdebug (2.5.0-r1)
demo_1  | OK: 176 MiB in 82 packages
demo_1  | 2017-05-18 22:24:49,310 CRIT Set uid to user 0
demo_1  | 2017-05-18 22:24:49,323 INFO RPC interface 'supervisor' initialized
demo_1  | 2017-05-18 22:24:49,324 CRIT Server 'unix_http_server' running without any HTTP authentication checking
demo_1  | 2017-05-18 22:24:49,324 INFO supervisord started with pid 39
demo_1  | 2017-05-18 22:24:50,327 INFO spawned: 'php-fpm' with pid 42
demo_1  | 2017-05-18 22:24:50,330 INFO spawned: 'nginx' with pid 43
demo_1  | [18-May-2017 22:24:50] WARNING: Nothing matches the include pattern '/etc/php5/fpm.d/*.conf' from /etc/php5/php-fpm.conf at line 15.
demo_1  | [18-May-2017 22:24:50] ERROR: [/etc/php5/php-fpm.conf:544] empty value
demo_1  | [18-May-2017 22:24:50] ERROR: failed to load configuration file '/etc/php5/php-fpm.conf'
demo_1  | [18-May-2017 22:24:50] ERROR: FPM initialization failed
demo_1  | 2017-05-18 22:24:50,381 INFO exited: php-fpm (exit status 78; not expected)
demo_1  | 2017-05-18 22:24:51,385 INFO spawned: 'php-fpm' with pid 46
demo_1  | 2017-05-18 22:24:51,386 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
demo_1  | [18-May-2017 22:24:51] WARNING: Nothing matches the include pattern '/etc/php5/fpm.d/*.conf' from /etc/php5/php-fpm.conf at line 15.
demo_1  | [18-May-2017 22:24:51] ERROR: [/etc/php5/php-fpm.conf:544] empty value
demo_1  | [18-May-2017 22:24:51] ERROR: failed to load configuration file '/etc/php5/php-fpm.conf'
demo_1  | [18-May-2017 22:24:51] ERROR: FPM initialization failed
demo_1  | 2017-05-18 22:24:51,424 INFO exited: php-fpm (exit status 78; not expected)
demo_1  | 2017-05-18 22:24:53,429 INFO spawned: 'php-fpm' with pid 47
demo_1  | [18-May-2017 22:24:53] WARNING: Nothing matches the include pattern '/etc/php5/fpm.d/*.conf' from /etc/php5/php-fpm.conf at line 15.
demo_1  | [18-May-2017 22:24:53] ERROR: [/etc/php5/php-fpm.conf:544] empty value
demo_1  | [18-May-2017 22:24:53] ERROR: failed to load configuration file '/etc/php5/php-fpm.conf'
demo_1  | [18-May-2017 22:24:53] ERROR: FPM initialization failed
demo_1  | 2017-05-18 22:24:53,463 INFO exited: php-fpm (exit status 78; not expected)
demo_1  | 2017-05-18 22:24:56,469 INFO spawned: 'php-fpm' with pid 48
demo_1  | [18-May-2017 22:24:56] WARNING: Nothing matches the include pattern '/etc/php5/fpm.d/*.conf' from /etc/php5/php-fpm.conf at line 15.
demo_1  | [18-May-2017 22:24:56] ERROR: [/etc/php5/php-fpm.conf:544] empty value
demo_1  | [18-May-2017 22:24:56] ERROR: failed to load configuration file '/etc/php5/php-fpm.conf'
demo_1  | [18-May-2017 22:24:56] ERROR: FPM initialization failed
demo_1  | 2017-05-18 22:24:56,504 INFO exited: php-fpm (exit status 78; not expected)
demo_1  | 2017-05-18 22:24:57,507 INFO gave up: php-fpm entered FATAL state, too many start retries too quickly
demo_1  | 2017/05/18 22:33:22 [crit] 45#0: *1 connect() to unix:/var/run/php-fpm.sock failed (13: Permission denied) while connecting to upstream, client: 172.19.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost:8080"
demo_1  | 172.19.0.1 - - [18/May/2017:22:33:22 +0000] "GET / HTTP/1.1" 502 173 "-" "curl/7.51.0"

**Comment by coleca** [comment]
That would mean that one of the environment variables is not being set for some reason.

If you run 

`make exec`

Then

`tail -20 /etc/php5/php-fpm.conf`

You should be able to see which variable is empty which is causing PHP-FPM not to launch.

**Comment by rubemfsv** [comment]
/var/log # tail -20 /etc/php5/php-fpm.conf
;php_admin_flag[log_errors] = on
;php_admin_value[memory_limit] = 32M
env [no_proxy] = "*.local, 169.254/16"
env [HOSTNAME] = "xxx"
env [SHLVL] = "1"
env [HOME] = "/root"
env [XDEBUG_CONFIG] = "remote_host"
env [POLL_TIMEOUT] = "300"
env [AWS_S3_UPLOAD_BUCKET] = ""
env [APP_ID] = "xxx"
env [PATH] = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
env [XDEBUG] = "true"
env [STAGE] = "dev"
env [AWS_S3_REGION] = ""
env [DEMO1_ID] = ""
env [API_TIMEOUT] = "10"
env [PWD] = "/var/log"
env [APP_KEY] = "xxx"
env [DEMO_SECRET_KEY] = ""
env [API_URL] = "https://api.kairos.com"

**Comment by coleca** [comment]
Those variables (AWS_S3_UPLOAD_BUCKET, AWS_S3_REGION, and DEMO1_ID) are all being set in the docker-compose.yml file with defaults.  Even though they aren't particularly valid, they should still allow the app to come up.

https://github.com/kairosinc/api-examples/blob/master/docker-compose.yml

Something must be different on your system with those environment variables.

**Comment by rubemfsv** [comment]
Problem solved! 

Thank you for your help.
