### ISSUE TITLE
Comes error while app build 

### ISSUE THREAD

**Issue by nileshaut25** [kairosinc/api-examples#14]
First of all, thank you for making such a beautiful API,
I have to try to build and run an application on my local machine but giving me following error after hitting command _make build && make run_. I have used my application key and id also.

> docker build  -t demo .
> make: docker: No such file or directory
> make: *** [build] Error 1

**Comment by coleca** [comment]
Hi

You need to have Docker for Mac or Docker for Windows installed (or just Docker if on Linux).

**Comment by nileshaut25** [comment]
Ohh Thank You
