### ISSUE TITLE
Failed to execute script docker-compose make: *** [run] Error 255

### ISSUE THREAD

**Issue by nileshaut25** [kairosinc/api-examples#15]
Hey, I have hit make build && make run command and I got the error. Can please help me, I am using Mac PC.
Failed to execute script docker-compose
make: *** [run] Error 255

![screen shot 2017-06-27 at 12 23 17 pm](https://user-images.githubusercontent.com/11028379/27574382-c367e1e4-5b33-11e7-83c1-addd44ccf063.png)

**Comment by josue** [comment]
@nileshaut25 I did not have issues running the demo.

Please ensure you have the latest stable versions of Docker for Mac/Windows and Docker-Compose.

_Please see below my screencast on my quick demo installation just now._

----
Tested successfully via:
- macOS Sierra (10.12.5)
- Docker version **17.03.1-ce**, build c6d412e
- Docker-Compose version **1.11.2**, build dfed245

See screencast example setup:
[![asciicast](https://asciinema.org/a/XU6OwAXNyeXkGDmrRywhdxRfK.png)](https://asciinema.org/a/XU6OwAXNyeXkGDmrRywhdxRfK)

Browser preview:
<img width="656" alt="" src="https://user-images.githubusercontent.com/21935/27576435-f8ea2910-5aea-11e7-8e9c-57e19b7081e7.png">

**Comment by nileshaut25** [comment]
Thank you josue,

I check my version and its latest but when I hit the `docker-compose --version` command  I got the error. Thank you


```
Nileshs-MacBook-Pro:~ Nilesh$ docker-compose --version
Traceback (most recent call last):
  File "docker-compose", line 2, in <module>
  File "/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-build-MW5H3j/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "compose/cli/__init__.py", line 16, in <module>
  File "subprocess.py", line 711, in __init__
  File "subprocess.py", line 1343, in _execute_child
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
Failed to execute script docker-compose
```

**Comment by josue** [comment]
It seems others have similar issues as you are having: https://github.com/docker/compose/issues/4663

Try resetting your Docker for Mac and/or Docker-Compose, or reinstall both, then try again.

**Comment by nileshaut25** [comment]
Reinstalling Docker and its working perfectly.
Thank you Josue for your support
