### ISSUE TITLE
API not recognising person in video.

### ISSUE THREAD

**Issue by rudrikpatel** [kairosinc/api-examples#18]
Whenever I tried to upload a video which is recorded from the front camera of the Android mobile device, API doesn't seem to recognise to person and giving me no person found in video error in the response.

Any workaround regarding this issue?

**Comment by steverucker** [comment]
Currently, the webcam functionality for the demos only applies to desktop.  We will make this more clear in future commits.

**Comment by rudrikpatel** [comment]
Ok, Good to know.
