### ISSUE TITLE
Kairos API : subject_id one or more required parameters are missing

### ISSUE THREAD

**Issue by mschaudhari** [kairosinc/api-examples#19]
I'm trying to enroll person profile pic's using [https://kairos.docs.apiary.io/#reference/face-recognition](url) API. I have a following python code. 
 
**My python script:**

    #!/usr/bin/python3
        
    import requests
    import io
    import http.client
    import base64
    import json
    import glob, os
    from os.path import basename
    
    dir_path = "/home/Kairos/profiles/msc/" 
    
    os.chdir(dir_path)
    
    for file in glob.glob("*.*"):
        img_path = file
        print(img_path)
        files = {'image': (img_path, open(dir_path + img_path, 'rb'), 'image/jpg', {'Expires': '0'})}
    
        headers = {
            'app_id': "xxxx",
            'app_key': "xxxxxxxxxxxxxxxxxxxxxx",
        }
    
        values_enrol = {
           'subject_id':'msc',
           'gallery_name':'mscGallary'
        }
    
        res = requests.post('https://api.kairos.com/enroll', headers=headers, files=files, data=values_enrol)
    
        print(res.content)

But, I'm getting an error :

     "Errors": [
            {
                "ErrCode": 1002,
                "Message": "subject_id one or more required parameters are missing"
            },
            {
                "ErrCode": 1002,
                "Message": "gallery_name one or more required parameters are missing"
            }
        ]
    }

What am I doing wrong here? Thanks in advance.

**Comment by tueaii** [comment]
Your values_enrol variable should be a UTF-8 string. Try

`
values_enrol = "{\"'subject_id\": \"msc \", \"gallery_name\": \"mscGallary\"}"
`
`
values_enrol = unicode(values_enrol, "utf-8")
`

**Comment by pawarmaheshkumar321** [comment]
Kairos requires publicly accessible Image url. You must upload image to your website first then pass that url in "image" parameter
