### ISSUE TITLE
Upload local media to /v2/media via curl

### ISSUE THREAD

**Issue by elelias** [kairosinc/api-examples#3]
It's not clear (to me) what the source parameter should look like when referencing local media, I have tried several things, via both cURL and postman, to no avail. Would you be so kind to provide a working example?

Thanks.

**Comment by coleca** [comment]
For the /media methods we need a form upload not a base64 encoded file.  

In curl it would look something like this:

curl -X POST -H "app_id: XXX" -H "app_key: YYY" -F "source=@myimage.jpg" "https://api.kairos.com/media/v2"
