### ISSUE TITLE
How can I run locally using Xampp?

### ISSUE THREAD

**Issue by iHirenDev** [kairosinc/api-examples#6]
Hello,
I am having an issue regarding running locally on my Mac. I have followed all the instruction from readme file. I have successfully run make and build command using docker. Now the thing is that I don't know how to run it locally.
Is there any document or step by step guide for How can I use Kairos api using Xampp?
Thanks in advance.

**Comment by coleca** [comment]
Hi,

If you look at the Dockerfile it is a blueprint on how to setup your environment with MAMP/XAMP/etc.  It needs some libraries to be installed in your local PHP installation such as Imagick, GD, EXIF, etc.
