### ISSUE TITLE
Bad gateway error Nginx

### ISSUE THREAD

**Issue by karanrai** [kairosinc/api-examples#7]
I followed the steps but on running the demo, the nginx server reports a 502 Bad Gateway error.

I noticed it was because the PHP-FPM was failing to initialise
`bash-4.3# /usr/bin/php-fpm -c /etc/php5
[30-Mar-2017 09:11:05] WARNING: Nothing matches the include pattern '/etc/php5/fpm.d/*.conf' from /etc/php5/php-fpm.conf at line 15.
[30-Mar-2017 09:11:05] ERROR: [/etc/php5/php-fpm.conf:547] empty value
[30-Mar-2017 09:11:05] ERROR: failed to load configuration file '/etc/php5/php-fpm.conf'
[30-Mar-2017 09:11:05] ERROR: FPM initialization failed`

I looked up the php-fpm.conf file at line number 547 and I noticed the `DEMO_ID` env variable was empty.

So I noticed that 2 environment variables `DEMO_ID` and `DEMO_SECRET_KEY` are not being set which is causing the FPM initialization to fail. If I comment these config variables, the server starts. However the api calls fail.

On further investigation I noticed the problem starts with docker-compose.yml file where the values are not set. Are these supposed to be the same values as the `APP_ID` and `APP_SECRET_KEY` ? If I do that the Emotion demo doesn't work. Others still work.

**Comment by steverucker** [comment]
Hi karanrai,

Sorry you're having issues with our example code.  We're currently making updates to the code, but for now you can run the demos - emotion, detect, recognize, verify - in a local server environment such as MAMP, WAMP or XAMP.   Make sure you go to https://www.kairos.com/ and get your free API_ID and APP_KEY.  Insert those in the config.php file, and set the API_URL to api.kairos.com.  Let us know if you have further difficulty.
