### ISSUE TITLE
http://localhost:8080:80 is not working as your tutorial

### ISSUE THREAD

**Issue by rubemfsv** [kairosinc/api-examples#9]
I'm following the following tutorial, and its not working. 
I'm doing everything good, but it still don't working. How can I solve this problem?

https://github.com/kairosinc/api-examples/blob/master/demo/emotion/README.md

**Comment by josue** [comment]
Thanks for pointing out the incorrect localhost url. The correct url should be `http://localhost:8080` 

The README is now updated.
